### ISSUE TITLE
null pointer when given wonky csv

### ISSUE THREAD

**Issue by efx** [tomszilagyi/banks2ledger#1]
I was confused by this for a few minutes, so I figured I would post here. The CSV export seems invalid from my bank, but it would help to have clearer error handling so I can figure that out quicker. My bank gave me the following text as a CSV export:
```csv
"Postdate","Description","Confirmation","Amount","Check Number"

01/17/2017,"SHR DRAFT - SHARE DRAFT","=TEXT(0000,0)","-30","1903"  
02/01/2017,"JRNL ENTRY - SHARE DRAFT DEP FROM CASH RECEIVED","=TEXT(000,0)","260",""  

```

running the following command		 
```
java -jar ~/banks2ledger/target/uberjar/banks2ledger-1.0.0-standalone.jar \
			 -a "Assets:Foo" \
			 -l myledger.dat \
			 -f export.csv \
			 -t '%1' \
			 -d 0 \
			 -m 2 \
 			 -sa 2 \
			 -D 'mm/dd/yyyy' \
			 -c '$'
```
gave me this trace:
```
Exception in thread "main" java.lang.NullPointerException
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301)
	at banks2ledger.core$tokenize.invokeStatic(core.clj:34)
	at banks2ledger.core$tokenize.invoke(core.clj:30)
	at banks2ledger.core$parse_ledger_entry.invokeStatic(core.clj:108)
	at banks2ledger.core$parse_ledger_entry.invoke(core.clj:104)
	at clojure.core$map$fn__4785.invoke(core.clj:2644)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$reduce.invoke(core.clj:6527)
	at banks2ledger.core$parse_ledger.invokeStatic(core.clj:120)
	at banks2ledger.core$parse_ledger.invoke(core.clj:115)
	at banks2ledger.core$_main.invokeStatic(core.clj:344)
	at banks2ledger.core$_main.doInvoke(core.clj:342)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at banks2ledger.core.main(Unknown Source)
```

**Comment by tomszilagyi** [comment]
That's weird. I just tried and cannot reproduce your issue.
```
$ cat test.csv 
"Postdate","Description","Confirmation","Amount","Check Number"

01/17/2017,"SHR DRAFT - SHARE DRAFT","=TEXT(0000,0)","-30","1903"
02/01/2017,"JRNL ENTRY - SHARE DRAFT DEP FROM CASH RECEIVED","=TEXT(000,0)","260",""
$ java -jar target/uberjar/banks2ledger-1.0.0-standalone.jar -a "Assets:Foo" -l empty.dat -f test.csv -t '%1' -d 0 -m 2 -sa 2 -D 'mm/dd/yyyy' -c '$'
2017/01/17 SHR DRAFT - SHARE DRAFT
    Assets:Foo                            $ 0.00
    Unknown

2017/01/01 JRNL ENTRY - SHARE DRAFT DEP FROM CASH RECEIVED
    Assets:Foo                            $ 0.00
    Unknown
```

I can even put in nonzero numbers inside the `=TEXT()` and they parse:
```
$ cat test.csv 
"Postdate","Description","Confirmation","Amount","Check Number"

01/17/2017,"SHR DRAFT - SHARE DRAFT","=TEXT(1234,5)","-30","1903"
02/01/2017,"JRNL ENTRY - SHARE DRAFT DEP FROM CASH RECEIVED","=TEXT(678,9)","260",""
$ java -jar target/uberjar/banks2ledger-1.0.0-standalone.jar -a "Assets:Foo" -l empty.dat -f test.csv -t '%1' -d 0 -m 2 -sa 2 -D 'mm/dd/yyyy' -c '$'
2017/01/17 SHR DRAFT - SHARE DRAFT
    Assets:Foo                            $ 1,234.50
    Unknown

2017/01/01 JRNL ENTRY - SHARE DRAFT DEP FROM CASH RECEIVED
    Assets:Foo                            $ 678.90
    Unknown
```

This is what I'm on:
```
$ lein version
Leiningen 2.6.1 on Java 1.7.0_95 OpenJDK 64-Bit Server VM
```

**Comment by efx** [comment]
hmmm, I truncated the CSV for privacy but perhaps it was a later line. I can check later today and update.

**Comment by tomszilagyi** [comment]
According to the stacktrace, it is `parse-ledger-entry` that fails, so I would assume that the cause of the exception lies in one of the lines in your ledger. You can easily check if it is your ledger file by supplying an empty file instead (that's what I did with `-l empty.dat`; I just created that with `touch empty.dat`). My theory is that the program will run (but of course all the inferred account names will be `Unknown`).

Incidentally, I managed to get a very similar stacktrace by setting `-m 4` (instead of your `-m 2`) with the above example, which fails because on the second line the last value is `""` which also upsets the parser, this time in `parse_csv_entry` as expected.

It would be helpful if you could give me the one-liner from your ledger file that causes your problem, and then I could fix the code to give a more helpful error message in both cases.

**Comment by efx** [comment]
`Leiningen 2.7.1 on Java 1.8.0_121 OpenJDK 64-Bit Server V`
thanks for the help! Sure enough, it errors when referencing my ledger file. but succeeds when using an empty ledger file. Sometime next week I'll try to dig into it and see what might be causing it. For reference, I am embedding all my `account` and `tag` directives at the top of the ledger file.

**Comment by tomszilagyi** [comment]
That explains it! Banks2ledger currently does not have a full-fledged ledger parser, it only understands the normal transactions (that's what I have, so I didn't need to do more). I can look into implementing more of the ledger file format, just to be able to ignore those parts that are not needed. In the meantime, you could put all of your non-transactions stuff at the top of your ledger file, and then use something like `tail -n +N ledger.dat` to produce a stripped file suitable for feeding into banks2ledger, where `N` is the number of lines you want to skip at the top.

**Comment by efx** [comment]
ah, excellent; I'll definitely try that tail -n trick. Thanks again!
