### ISSUE TITLE
use clojure.data.csv?

### ISSUE THREAD

**Issue by jmarca** [tomszilagyi/banks2ledger#2]
Hi.  Nice app.  It works for me but only if I first do lots of cleaning of my bank's CSV output (they quote every entry for some reason).  

I think the parser would be more robust for ugly CSV if you used the "official" parsing library clojure.data.csv, rather than hand-parsing the CSV lines.

(I'm trying to insert it, but doing so requires lots of little changes, perhaps too many for a nice neat patch.  Plus I am going to break up your code into lots of little files so I can get a clue what is going on (what I have so far isn't working) which will further reduce the utility of a patch.)

**Comment by tomszilagyi** [comment]
Hi James,

I agree that migrating the parsing to use clojure.data.csv would be a
sensible move.

However, if you are working towards a PR that you'd like to see merged,
please don't break up the code into several files, just do the parsing
migration.

2018-03-07 2:29 GMT+01:00 James Marca <notifications@github.com>:

**Comment by jmarca** [comment]
well, I had no clue, but I figured it out by sticking print statements everywhere.  Patch coming in a bit, should be fairly clean (I hope).  Feel free to take from it what you want and/or merge the whole thing.
